name: Preprocess, build and deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Preprocess the text
      run: |
        cd skriptovi
        node index.js
        cd ..

    - name: Run Jekyll
      uses: theikeofficial/action-jekyll@master

    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      secrets:
        GH_PAT: ${{ secrets.GH_PAT }}
      with:
        BUILD_DIR: _site
